### ISSUE TITLE
Mutect 4.0.0.0 support

### ISSUE THREAD

**Issue by elifirem** [morrislab/phylowgs#83]
Hi,
I want to use PhyloWGS on some vcf files that I've created with Mutect 4.0.0.0 (tumor-normal comparison), but I am guessing the parser is not supporting this version yet? I've tried calling
`create_phylowgs_inputs.py --vcf-type sample1=mutect_tcga` for a try, and the error line is:

`File "/cm/shared/apps/phylowgs/1.0/parser/create_phylowgs_inputs.py", line 1356, in <module>
    main()
  File "/cm/shared/apps/phylowgs/1.0/parser/create_phylowgs_inputs.py", line 1301, in main
    variant_ids, ref_read_counts, total_read_counts = parse_variants(samples, vcf_files, vcf_types, args.tumor_sample, args.missing_variant_confidence)
  File "/cm/shared/apps/phylowgs/1.0/parser/create_phylowgs_inputs.py", line 1182, in parse_variants
    parsed_variants.append(variant_parser.list_variants())
  File "/cm/shared/apps/phylowgs/1.0/parser/create_phylowgs_inputs.py", line 33, in list_variants
    ref_reads, total_reads = self._calc_read_counts(variant)
  File "/cm/shared/apps/phylowgs/1.0/parser/create_phylowgs_inputs.py", line 236, in _calc_read_counts
    ref_reads, variant_reads = variant.samples[tumor_i]['TD']
  File "/cm/shared/apps/python/2.7.12/lib/python2.7/site-packages/vcf/model.py", line 104, in __getitem__
    return getattr(self.data, key)
AttributeError: 'CallData' object has no attribute 'TD'`

I see that your mutect_tcga test input file has TD:ND:TR:NR in its format field while my vcf file looks like this:

#CHROM | POS | ID | REF | ALT | QUAL | FILTER | INFO | FORMAT
1 | 897455 | . | CCCCCA | C | . | mapping_quality;str_contraction;t_lod | DP=180;ECNT=1;NLOD=3.25;N_ART_LOD=-1.162e+00;POP_AF=3.693e-04;P_GERMLINE=-3.265e+00;RPA=4,3;RU=CCCCA;STR;TLOD=3.12 | **GT:AD:AF:F1R2:F2R1:MBQ:MFRL:MMQ:MPOS:OBAM:OBAMRC:SA_MAP_AF:SA_POST_PROB**

How can I solve this problem and do you have any suggestions? Thanks!
Irem

**Comment by jwintersinger** [comment]
Hi @elifirem,

Can you upload an example VCF from MuTect 4, please? It only needs to have a couple variants in it. We'll try to add support then.

Thanks!

**Comment by elifirem** [comment]
Hi @jwintersinger thank you for the reply. Can I share them privately via email, would that be ok?

**Comment by elifirem** [comment]
If sample type is specified as mutect_smchet, it works fine with Mutect 4.0.0.0 outputs.
